### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by yevhen** [Genbox/CSharpFastPFOR#2]
How is this code licensed? Can I use it in a commercial project?

**Comment by Genbox** [comment]
It has the same license as the original project written by Daniel Lemire over at https://github.com/lemire/JavaFastPFOR, which is Apache License Version 2.0

**Comment by lemire** [comment]
@Genbox Maybe you want to make this explicit by uploading a LICENSE file?

Ambiguity regarding the licensing terms makes it harder for some people to use the library.

**Comment by Genbox** [comment]
@lemire, I'll upload a license and link back to your repo as well.

**Comment by yevhen** [comment]
Thanks!
