### ISSUE TITLE
Consider joining fast-pack org?

### ISSUE THREAD

**Issue by nyurik** [Genbox/CSharpFastPFOR#5]
Recently @lemire, author of the core fastpfor algorithm, transferred all his code to the new github org [fast-pack](https://github.com/fast-pack).  Would it make sense to move this project to that org too, so that all implementations can be kept closer together and maintained by a community?  Current project admins will continue being admins after the transfer, and we could automate publishing to the package registry. Thx!

**Comment by lemire** [comment]
I support this.

**Comment by Genbox** [comment]
Sounds good to me. Thanks for confirming @lemire. I'll transfer ownership to the fast-pack org.

**Comment by Genbox** [comment]
I'll need permission to create public repos in the org before transferring.

**Comment by lemire** [comment]
@Genbox I have invited you.

**Comment by Genbox** [comment]
Transfer completed. Can you re-add me as a maintainer for the project?

**Comment by lemire** [comment]
@Genbox Done!

**Comment by Genbox** [comment]
That was quick! Happy New Year :)
